DROP TABLE IF EXISTS Events;
DROP TABLE IF EXISTS Artists;

CREATE TABLE Artists
(
  ID   INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(20),
  Fee  DOUBLE,
  PRIMARY KEY (id)
);

CREATE TABLE Events
(
  ID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(20),
  Date DATE,
  StartTime TIME,
  FinishTime TIME,
  ArtistID INT,
  PRIMARY KEY (ID),
  FOREIGN KEY (ArtistID) REFERENCES Artists(ID)
);